export const COM_CREATE_CHAT_REQUEST = "COM_CREATE_CHAT_REQUEST";
export const COM_CREATE_CHAT_SUCCESS = "COM_CREATE_CHAT_SUCCESS";
export const COM_CREATE_CHAT_FAIL = "COM_CREATE_CHAT_FAIL";

export const COM_FIND_CHAT_REQUEST = "COM_FIND_CHAT_REQUEST";
export const COM_FIND_CHAT_SUCCESS = "COM_FIND_CHAT_SUCCESS";
export const COM_FIND_CHAT_FAIL = "COM_FIND_CHAT_FAIL";
export const COM_FIND_CHAT_RESET = "COM_FIND_CHAT_RESET";

export const COM_SEND_MESSAGE_REQUEST = "COM_SEND_MESSAGE_REQUEST";
export const COM_SEND_MESSAGE_SUCCESS = "COM_SEND_MESSAGE_SUCCESS";
export const COM_SEND_MESSAGE_FAIL = "COM_SEND_MESSAGE_FAIL";
export const COM_SET_CHATS_SUCCESS = "COM_SET_CHATS_SUCCESS";
export const COM_SEND_MESSAGE_RESET = "COM_SEND_MESSAGE_RESET";
