//! Basic User Actions
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";
export const USER_PROFILE_RESET = "USER_PROFILE_RESET";

// !Friend Constants
export const USER_ADD_FRIEND_INFO = "USER_ADD_FRIEND_INFO";
export const USER_ADD_FRIEND_RESET = "USER_ADD_FRIEND_RESER";

export const REMOVE_FRIEND_REQUEST = "REMOVE_FRIEND_REQUEST";
export const REMOVE_FRIEND_SUCCESS = "REMOVE_FRIEND_SUCCESS";
export const REMOVE_FRIEND_FAIL = "REMOVE_FRIEND_FAIL";
export const REMOVE_FRIEND_RESET = "REMOVE_FRIEND_RESET";

//! Manage Friend Request
export const USER_UPDATE_FRIEND_REQUEST = "USER_UPDATE_FRIEND_REQUEST";

export const USER_SEARCH_FRIEND_SUCCESS = "USER_SEARCH_FRIEND_SUCCESS";
export const USER_SEARCH_FRIEND_FAIL = "USER_SEARCH_FRIEND_FAIL";
export const USER_SEARCH_FRIEND_RESET = "USER_SEARCH_FRIEND_RESET";

export const USER_ADD_FRIEND_REQUEST_SUCCESS =
  "USER_ADD_FRIEND_REQUEST_SUCCESS";
export const USER_ADD_FRIEND_REQUEST_FAIL = "USER_ADD_FRIEND_REQUEST_FAIL";
export const USER_ADD_FRIEND_REQUEST_RESET = "USER_ADD_FRIEND_REQUEST_RESET";

export const USER_ACCEPT_FRIEND_REQUEST_SUCCESS =
  "USER_ACCEPT_FRIEND_REQUEST_SUCCESS";
export const USER_ACCEPT_FRIEND_REQUEST_FAIL =
  "USER_ACCEPT_FRIEND_REQUEST_FAIL";
export const USER_ACCEPT_FRIEND_REQUEST_RESET =
  "USER_ACCEPT_FRIEND_REQUEST_RESET";

export const USER_DECLINE_FRIEND_REQUEST_SUCCESS =
  "USER_DECLINE_FRIEND_REQUEST_SUCCESS";
export const USER_DECLINE_FRIEND_REQUEST_FAIL =
  "USER_DECLINE_FRIEND_REQUEST_FAIL";
export const USER_DECLINE_FRIEND_REQUEST_RESET =
  "USER_DECLINE_FRIEND_REQUEST_RESET";

//! User Notifications
export const USER_UPDATE_NOTIFICATIONS_REQUEST =
  "USER_UPDATE_NOTIFICATIONS_REQUEST";

export const USER_CLEAR_NOTIFICATIONS_SUCCESS =
  "USER_CLEAR_NOTIFICATIONS_SUCCESS";
export const USER_CLEAR_NOTIFICATIONS_FAIL = "USER_CLEAR_NOTIFICATIONS_FAIL";
export const USER_CLEAR_NOTIFICATIONS_RESET = "USER_CLEAR_NOTIFICATIONS_RESET";
